### ISSUE TITLE
To-Do: do everything to accomplish

### ISSUE THREAD

**Issue by ervinMamutov** [ervinMamutov/bf-inside-js#1]
- [x] lesson-plans
  - [x] for-loops
  - [x] functional-array-methods
  - [x] functions-and-unit-testing
  - [x] side-effects

- [x] 0-asserting
- [x] 1-primitives-and-operators
- [x] 2-control-flow
- [x] 3-functions
- [x] 4-unit-testing
- [x] 5-es-modules
- [x] 6-using-functions
- [x] 7-arrays
- [x] 8-functional-array-methods
- [x] 9-multiple-interactions
