### ISSUE TITLE
to-do:  lesson-plans

### ISSUE THREAD

**Issue by ervinMamutov** [ervinMamutov/bf-inside-js#2]
- [x]  create `for-loops`
  - [x] 1-isolate
    - [x] count-to-10-in-5-steps.js
    - [x] loop-head-syntax.js
    - [x] reverse-a-string.js
  - [x] 2-integrate
 
 - [x] functions-and-unit-testing
   - [x] 1-functions
     - [x] 0-example-scramble.js
     - [x] 1-write-expected.js
     - [x] 2-write-arguments.js
     - [x] 3-write-function.js 
   - [x] 2-documenting-functions
     - [x] 1-long-or-short.js
     - [x] 2-is-palindrome.js
     - [x] 3-count-character.js 
   - [x] 3-testing-functions
     - [x] 1-repeat-string.test.js
     - [x] 2-repeat-characters.test.js
     - [x] 3-repeat-repeat.test.js
