### ISSUE TITLE
to-do : lesson-plans

### ISSUE THREAD

**Issue by ervinMamutov** [ervinMamutov/bf-inside-js#21]
- [x] create branch `lesson-plans-week3`
- [x] util-functions
  - [x] 1-primitives
  - [x] 2-array-and-object
- [x] group-project-intro
- [x] sabotage
